spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

allowed:
  path: /api/task/**

auth:
  tokenName: auth_token
  tokenValue: web-c1696899-d015-47c9-9472-9a665e28cef9

